#!/usr/bin/env python3
"""
Reproducible validation for Tier-3 (biological) numbers in main.tex.

Checks: SHA-256 of raw CSVs; enrichment scalars quoted in prose;
supplementary table regeneration; perturbation claim verification.

Run: wsl bash -lc 'source ~/miniconda3/etc/profile.d/conda.sh && conda activate gt && cd /mnt/d/cluster/ClusterNet/paper && python validate_biological_manuscript.py'
"""
from __future__ import annotations

import pathlib
import sys

import numpy as np
import pandas as pd

from bio_io import (
    ALGO_DISPLAY,
    GNN_ALGOS,
    NETWORK_ORDER,
    PATHS,
    file_fingerprint,
    load_enrichment_averaged,
    load_perturbation,
    perturbation_summary,
)
from gen_bio_table import enrichment_full_table, perturbation_table


def _tex_escape(s: str) -> str:
    return s.replace("\\", "/").replace("_", r"\_").replace("%", r"\%")


def check_approx(name: str, got: float, expected: float, tol: float = 0.03) -> tuple[str, bool]:
    ok = not (np.isnan(got) or np.isnan(expected)) and abs(got - expected) <= tol
    status = "PASS" if ok else "FAIL"
    return f"{name} & {expected:.4f} & {got:.4f} & {tol} & {status}", ok


def main() -> int:
    root = pathlib.Path(__file__).parent
    tables_dir = root / "tables"
    tables_dir.mkdir(exist_ok=True)

    lines: list[str] = []
    lines.append(r"\subsection{Automated validation (biological benchmark)}")
    lines.append(
        r"Generated by \texttt{validate\_biological\_manuscript.py}. "
        r"Every check recomputes from raw CSVs."
    )

    # --- Fingerprints ---
    lines.append(r"\subsubsection{Input files and SHA-256 checksums}")
    lines.append(r"\footnotesize")
    lines.append(r"\begin{tabular}{lp{8cm}rr}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Key} & \textbf{Path} & \textbf{Bytes} & \textbf{SHA-256 (prefix)} \\")
    lines.append(r"\midrule")
    all_ok = True
    for key, path in sorted(PATHS.items()):
        fp = file_fingerprint(path)
        if not fp["exists"]:
            all_ok = False
            lines.append(
                rf"{_tex_escape(key)} & \texttt{{{_tex_escape(str(path))}}} & --- & \textbf{{MISSING}} \\"
            )
            continue
        sha_pfx = fp["sha256"][:16] + r"\ldots"
        path_tt = _tex_escape(pathlib.Path(path).as_posix())
        lines.append(
            rf"{_tex_escape(key)} & \texttt{{{path_tt}}} & {fp['size_bytes']} & \texttt{{{sha_pfx}}} \\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\normalsize")

    # --- Enrichment checks ---
    lines.append(r"\subsubsection{Enrichment scalars (main text prose)}")
    lines.append(r"\begin{tabular}{p{7cm}rrrr}")
    lines.append(r"\toprule")
    lines.append(r"Claim & Expected & Got & Tol & Status \\")
    lines.append(r"\midrule")

    df = load_enrichment_averaged()

    def _go(net, algo):
        r = df[(df["network"] == net) & (df["algorithm"] == algo)]
        return float(r["go_enriched_frac"].iloc[0]) if len(r) > 0 else float("nan")

    def _kegg(net, algo):
        r = df[(df["network"] == net) & (df["algorithm"] == algo)]
        return float(r["kegg_enriched_frac"].iloc[0]) if len(r) > 0 else float("nan")

    def _sign(net, algo):
        r = df[(df["network"] == net) & (df["algorithm"] == algo)]
        return float(r["sign_coherence"].iloc[0]) if len(r) > 0 else float("nan")

    def _mean_go_type(net, typ):
        sub = df[(df["network"] == net) & (df["type"] == typ)]
        return float(sub["go_enriched_frac"].mean()) if len(sub) > 0 else float("nan")

    checks = [
        # BioGRID classical top
        (r"Leiden GO on BioGRID", 1.0, _go("biogrid", "leiden")),
        (r"Louvain GO on BioGRID", 1.0, _go("biogrid", "louvain")),
        (r"RB-Pots GO on BioGRID", 1.0, _go("biogrid", "rb_pots")),
        # GNN vs classical means
        (r"GNN mean GO on SIGNOR", 0.97, _mean_go_type("signor", "GNN")),
        (r"Classical mean GO on SIGNOR", 0.80, _mean_go_type("signor", "Classical")),
        (r"GNN mean GO on GRN", 0.96, _mean_go_type("grn", "GNN")),
        (r"Classical mean GO on GRN", 0.73, _mean_go_type("grn", "Classical")),
        (r"GNN mean GO on BioGRID", 0.99, _mean_go_type("biogrid", "GNN")),
        (r"Classical mean GO on BioGRID", 0.83, _mean_go_type("biogrid", "Classical")),
        (r"GNN mean GO on GTEx", 0.55, _mean_go_type("gtex_0.9", "GNN")),
        (r"Classical mean GO on GTEx", 0.57, _mean_go_type("gtex_0.9", "Classical")),
        # SBM enrichment
        (r"SBM GO on SIGNOR", 1.0, _go("signor", "sbm")),
        (r"Nested SBM GO on SIGNOR", 1.0, _go("signor", "nested_sbm")),
        # Sign coherence
        (r"SCAN sign coherence on SIGNOR", 0.88, _sign("signor", "scan")),
        (r"MLP+KM sign coherence on SIGNOR", 0.87, _sign("signor", "mlp_kmeans")),
        (r"Label Prop sign coherence on SIGNOR", 0.87, _sign("signor", "label_propagation")),
        (r"SBM sign coherence on SIGNOR", 0.66, _sign("signor", "sbm")),
        (r"Nested SBM sign coherence on SIGNOR", 0.69, _sign("signor", "nested_sbm")),
    ]

    for name, exp, got in checks:
        row, ok = check_approx(name, got, exp, tol=0.03)
        lines.append(row + r" \\")
        all_ok = all_ok and ok

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # --- Perturbation checks ---
    lines.append(r"\subsubsection{Perturbation claims (Figure~\ref{fig:bio\_perturbation})}")
    lines.append(r"\begin{tabular}{p{7cm}rrrr}")
    lines.append(r"\toprule")
    lines.append(r"Claim & Expected & Got & Tol & Status \\")
    lines.append(r"\midrule")

    ps = perturbation_summary()

    def _nmi(test, algo):
        r = ps[(ps["test"] == test) & (ps["algorithm"] == algo)]
        return float(r["nmi"].iloc[0]) if len(r) > 0 else float("nan")

    def _ffl_orig(test, algo):
        r = ps[(ps["test"] == test) & (ps["algorithm"] == algo)]
        return float(r["ffl_preserved_orig"].iloc[0]) if len(r) > 0 else float("nan")

    def _ffl_change(test, algo):
        r = ps[(ps["test"] == test) & (ps["algorithm"] == algo)]
        return float(r["ffl_change"].iloc[0]) if len(r) > 0 else float("nan")

    perturb_checks = [
        # DGI robustness
        (r"DGI NMI under TF-KO-5", 0.57, _nmi("tf_knockout_top5", "dgi_gnn")),
        # FastGreedy stability
        (r"FastGreedy NMI under random-5 ctrl", 0.75, _nmi("tf_knockout_control_random5", "fastgreedy")),
        # Hub removal catastrophic
        (r"Hub 5\% NMI Leiden", 0.12, _nmi("gene_removal_hub_0.05", "leiden")),
        # MinCut FFL baseline
        (r"MinCut baseline FFL preserved", 0.47, _ffl_orig("tf_knockout_top5", "mincut_gnn")),
    ]

    for name, exp, got in perturb_checks:
        row, ok = check_approx(name, got, exp, tol=0.05)
        lines.append(row + r" \\")
        all_ok = all_ok and ok

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # --- Table regeneration ---
    lines.append(r"\subsubsection{Supplementary tables match script output}")
    e_disk = (tables_dir / "bio_enrichment_full.tex").read_text(encoding="utf-8").strip()
    e_new = enrichment_full_table().strip()
    p_disk = (tables_dir / "bio_perturbation.tex").read_text(encoding="utf-8").strip()
    p_new = perturbation_table().strip()
    e_match = e_disk == e_new
    p_match = p_disk == p_new
    if not e_match or not p_match:
        all_ok = False
    lines.append(
        rf"Enrichment table S6 match: \textbf{{{'PASS' if e_match else 'FAIL'}}}. "
        rf"Perturbation table S7 match: \textbf{{{'PASS' if p_match else 'FAIL'}}}. "
        r"If FAIL, run \texttt{python gen\_bio\_table.py}."
    )

    # --- Overall ---
    lines.append(r"\subsubsection{Overall validation outcome}")
    lines.append(
        rf"\textbf{{Validation score: {'PASS' if all_ok else 'FAIL'}}} "
        r"(all files present, prose checks within tolerance, tables in sync)."
    )

    out_tex = tables_dir / "bio_validation_report.tex"
    out_tex.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_tex}")
    print(f"Overall validation: {'PASS' if all_ok else 'FAIL'}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
