#!/usr/bin/env python3
"""
Reproducible validation for Tier~2 (social) numbers and supplementary tables.

Verifies (when PASS): SHA-256 of raw CSVs; internal consistency (seeds, Node2Vec);
dataset statistics table vs ``metadata.json``; every AMI scalar used in Tier~2 prose
(main.tex Results); byte-identical regeneration of S3--S5 + ``social_main_top5.tex``.
Figures use the same loaders but are not pixel-tested.

Run: wsl bash -lc 'source ~/miniconda3/etc/profile.d/conda.sh && conda activate gt && cd /mnt/d/cluster/ClusterNet/paper && python validate_social_manuscript.py'
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
from gen_social_table import classical_wide_table, gnn_ablation_table, top_per_network_tex
from social_io import (
    FEATURE_ORDER,
    NETWORK_ORDER,
    file_fingerprint,
    load_classical_filtered,
    load_dataset_metadata,
    load_gnn,
    metadata_path,
    path_classical,
    path_gnn,
)


def _tex_escape(s: str) -> str:
    return s.replace("\\", "/").replace("_", r"\_").replace("%", r"\%")


def _mean_ami_gnn(net: str, algo: str, ft: str) -> float:
    gn = load_gnn()
    sub = gn[(gn["network"] == net) & (gn["algorithm"] == algo) & (gn["feature_type"] == ft)]
    sub = sub[sub["success"] & sub["ami"].notna()]
    return float(sub["ami"].mean()) if len(sub) else float("nan")


def _mean_ami_classical(net: str, algo: str) -> float:
    cl = load_classical_filtered()
    sub = cl[(cl["network"] == net) & (cl["algorithm"] == algo)]
    sub = sub[sub["success"] & sub["ami"].notna()]
    return float(sub["ami"].mean()) if len(sub) else float("nan")


def check_approx(name: str, got: float, expected: float, tol: float = 0.02) -> tuple[str, bool]:
    ok = not (np.isnan(got) or np.isnan(expected)) and abs(got - expected) <= tol
    status = "PASS" if ok else "FAIL"
    return f"{name} & {expected:.4f} & {got:.4f} & {tol} & {status}", ok


def check_exact_int(name: str, got: int, expected: int) -> tuple[str, bool]:
    ok = got == expected
    status = "PASS" if ok else "FAIL"
    return rf"{name} & {expected} & {got} & --- & {status}", ok


def main() -> int:
    root = pathlib.Path(__file__).parent
    td = root / "tables"
    td.mkdir(exist_ok=True)

    lines: list[str] = []
    lines.append(r"\subsection{Automated validation (social benchmark)}")
    lines.append(
        r"This section is generated by \texttt{validate\_social\_manuscript.py}. "
        r"Classical \texttt{sbm}, \texttt{nested\_sbm}, and \texttt{nested\_sbm\_coarse} are excluded from all aggregates "
        r"(graph-tool failures with Louvain fallback)."
    )

    lines.append(r"\subsubsection{Input files and SHA-256 checksums}")
    lines.append(r"\footnotesize")
    lines.append(r"\begin{tabular}{lp{8cm}rr}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{File} & \textbf{Path} & \textbf{Bytes} & \textbf{SHA-256 (prefix)} \\")
    lines.append(r"\midrule")
    all_ok = True
    for label, p in [("classical", path_classical()), ("gnn", path_gnn())]:
        fp = file_fingerprint(p)
        if not fp["exists"]:
            all_ok = False
            lines.append(
                rf"{_tex_escape(label)} & \texttt{{{_tex_escape(str(p))}}} & --- & \textbf{{MISSING}} \\"
            )
            continue
        sha_pfx = fp["sha256"][:16] + r"\ldots"
        path_tt = _tex_escape(pathlib.Path(p).as_posix())
        lines.append(
            rf"{_tex_escape(label)} & \texttt{{{path_tt}}} & {fp['size_bytes']} & \texttt{{{sha_pfx}}} \\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\normalsize")

    # --- Consistency checks (seed counts, node2vec invariance) ---
    lines.append(r"\subsubsection{Internal consistency checks}")
    gn = load_gnn()
    seed_counts = gn.groupby(["network", "algorithm", "feature_type"])["seed"].nunique()
    bad = seed_counts[seed_counts != 3]
    seeds_ok = len(bad) == 0
    if not seeds_ok:
        all_ok = False
    sc = "PASS" if seeds_ok else "FAIL"
    lines.append(
        rf"GNN rows: each (network, algorithm, feature\_type) has exactly 3 seeds: "
        rf"\textbf{{{sc}}}."
    )

    n2v_ok = True
    for net in NETWORK_ORDER:
        for ft in FEATURE_ORDER:
            m0 = _mean_ami_gnn(net, "node2vec_gnn", ft)
            m1 = _mean_ami_gnn(net, "node2vec_gnn", "real")
            if np.isnan(m0) or abs(m0 - m1) > 1e-6:
                n2v_ok = False
    if not n2v_ok:
        all_ok = False
    n2v_lbl = "PASS" if n2v_ok else "FAIL"
    lines.append(
        rf"Node2Vec+KM mean AMI invariant to feature type (topology-only): "
        rf"\textbf{{{n2v_lbl}}}."
    )

    lines.append(r"\subsubsection{Dataset statistics table (main text Table~\texttt{tab:social\_datasets})}")
    lines.append(
        r"The manuscript integers and rounded homophily values must match \texttt{metadata.json} "
        r"under \texttt{SocialNetworks/data/\{cora,citeseer,amazon\_photo\}/}."
    )
    lines.append(r"\begin{tabular}{p{6.8cm}rrrr}")
    lines.append(r"\toprule")
    lines.append(r"Field & Expected (main text) & Got (JSON) & Tol & Status \\")
    lines.append(r"\midrule")

    # Canonical displays hard-coded to match main.tex rounding conventions.
    manuscript_table = {
        "cora": {
            "nodes": 2708,
            "edges": 5278,
            "classes": 7,
            "features": 1433,
            "homophily_display": 0.81,
        },
        "citeseer": {
            "nodes": 3327,
            "edges": 4552,
            "classes": 6,
            "features": 3703,
            "homophily_display": 0.736,
        },
        "amazon_photo": {
            "nodes": 7650,
            "edges": 119081,
            "classes": 8,
            "features": 745,
            "homophily_display": 0.827,
        },
    }

    for net_id, mt in manuscript_table.items():
        prefix = f"{net_id}: "
        try:
            md = load_dataset_metadata(net_id)
        except OSError:
            all_ok = False
            row = (
                rf"{_tex_escape(prefix)}metadata.json present "
                rf"& --- & --- & --- & \textbf{{MISSING}} ({_tex_escape(str(metadata_path(net_id)))}) \\"
            )
            lines.append(row)
            continue

        pairs = [
            (f"{prefix}nodes", mt["nodes"], int(md["num_nodes"])),
            (f"{prefix}edges", mt["edges"], int(md["num_edges"])),
            (f"{prefix}classes", mt["classes"], int(md["num_classes"])),
            (f"{prefix}features", mt["features"], int(md["feature_dim"])),
        ]
        for name, exp, got in pairs:
            row, ok = check_exact_int(name, got, exp)
            lines.append(row + r" \\")
            all_ok = all_ok and ok

        rh = float(md["edge_homophily"])
        row_h, ok_h = check_approx(f"{prefix}homophily (display)", rh, float(mt["homophily_display"]), tol=0.001)
        lines.append(row_h + r" \\")
        all_ok = all_ok and ok_h

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # --- Headline numbers echoed in main text (update tolerances if CSV changes) ---
    lines.append(r"\subsubsection{AMI and prose scalars (Tier~2 results text)}")
    lines.append(r"\begin{tabular}{p{6.8cm}rrrr}")
    lines.append(r"\toprule")
    lines.append(r"Claim & Expected & Got & Tol & Status \\")
    lines.append(r"\midrule")

    checks = [
        (r"GAT AMI on Cora (real features, mean over 3 seeds)", 0.667, _mean_ami_gnn("cora", "gat_supervised", "real")),
        (r"GCN AMI on Cora (real features)", 0.650, _mean_ami_gnn("cora", "gcn_supervised", "real")),
        (r"GAT AMI on CiteSeer (real features)", 0.464, _mean_ami_gnn("citeseer", "gat_supervised", "real")),
        (r"GCN AMI on CiteSeer (real features)", 0.439, _mean_ami_gnn("citeseer", "gcn_supervised", "real")),
        (r"FastGreedy AMI on Cora (classical)", 0.445, _mean_ami_classical("cora", "fastgreedy")),
        (r"VGAE+KM AMI on Amazon Photo (real features)", 0.446, _mean_ami_gnn("amazon_photo", "vgae_gnn", "real")),
        (r"GAT AMI on Amazon Photo (real features)", 0.855, _mean_ami_gnn("amazon_photo", "gat_supervised", "real")),
        (r"GAT AMI on Amazon Photo with random features (mean)", 0.820, _mean_ami_gnn("amazon_photo", "gat_supervised", "random")),
        (r"GAT AMI on Cora with random features (mean)", 0.567, _mean_ami_gnn("cora", "gat_supervised", "random")),
        (r"GCN AMI on Amazon Photo (real features)", 0.698, _mean_ami_gnn("amazon_photo", "gcn_supervised", "real")),
        (r"GCN AMI on Amazon Photo with random features (mean)", 0.785, _mean_ami_gnn("amazon_photo", "gcn_supervised", "random")),
        (r"GCN AMI on Cora with random features (mean)", 0.523, _mean_ami_gnn("cora", "gcn_supervised", "random")),
        (r"Spinglass AMI on Amazon Photo (classical)", 0.665, _mean_ami_classical("amazon_photo", "spinglass")),
        (r"Louvain AMI on Amazon Photo (classical)", 0.658, _mean_ami_classical("amazon_photo", "louvain")),
    ]

    for name, exp, got in checks:
        tol = 0.03
        row, ok = check_approx(name, float(got), float(exp), tol=tol)
        lines.append(row + r" \\")
        all_ok = all_ok and ok

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    lines.append(r"\subsubsection{Supplementary tables match script output}")
    disk_c = (td / "social_classical_full.tex").read_text(encoding="utf-8").strip()
    new_c = classical_wide_table().strip()
    disk_g = (td / "social_gnn_ablation_full.tex").read_text(encoding="utf-8").strip()
    new_g = gnn_ablation_table().strip()
    disk_t = (td / "social_top_per_network.tex").read_text(encoding="utf-8").strip()
    new_t = top_per_network_tex(k=10).strip()
    disk_m = (td / "social_main_top5.tex").read_text(encoding="utf-8").strip()
    new_m = top_per_network_tex(k=5).strip()
    m1, m2, m3, m4 = disk_c == new_c, disk_g == new_g, disk_t == new_t, disk_m == new_m
    if not (m1 and m2 and m3 and m4):
        all_ok = False
    t1, t2, t3, t4 = ("PASS" if m1 else "FAIL"), ("PASS" if m2 else "FAIL"), (
        "PASS" if m3 else "FAIL"
    ), ("PASS" if m4 else "FAIL")
    lines.append(
        rf"Social classical wide table match: \textbf{{{t1}}}. "
        rf"GNN ablation table match: \textbf{{{t2}}}. "
        rf"Top-per-network (10) match: \textbf{{{t3}}}. Main top-5 snippet match: \textbf{{{t4}}}. "
        r"If FAIL, run \texttt{python gen\_social\_table.py}."
    )
    lines.append(
        r"\paragraph{Notes on coverage.} "
        r"A PASS here means (i)~every numeric cell in Supplementary Tables S3--S5 and in "
        r"\texttt{tables/social\_main\_top5.tex} is reproduced exactly by \texttt{gen\_social\_table.py} from the social CSVs; "
        r"(ii)~dataset counts and homophily match \texttt{metadata.json}; "
        r"(iii)~every AMI scalar quoted or rounded in Tier~2 running text is listed in the AMI table above. "
        r"Figures are driven by the same loaders (\texttt{plot\_social.py}), but pixels are not compared."
    )

    lines.append(r"\subsubsection{Overall validation outcome}")
    ov = "PASS" if all_ok else "FAIL"
    lines.append(
        rf"\textbf{{Validation score: {ov}}} "
        r"(CSVs present, metadata/dataset table and prose AMI checks, supplementary tables in sync)."
    )

    out_tex = td / "social_validation_report.tex"
    out_tex.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_tex}")
    print(f"Overall validation: {'PASS' if all_ok else 'FAIL'}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
