#!/usr/bin/env python3
"""
Reproducible validation of LFR numbers used in the manuscript.

Reads ONLY the CSV paths declared in lfr_io.PATHS, recomputes aggregates,
checks narrative claims, compares on-disk supplementary tables to regeneration,
and writes tables/lfr_validation_report.tex for inclusion in supplementary.pdf.

Run (recommended):  wsl bash -ic "conda activate gt && python validate_lfr_manuscript.py"

Exit code 1 if any automated check fails.
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
import pandas as pd

from gen_lfr_table import gen_accuracy_table, gen_scalability_table
from lfr_io import (
    AMI_OVERLAY_HIERARCHICAL_CLASSICAL,
    PATHS,
    ami_mean,
    ami_mean_scalability,
    file_fingerprint,
    load_gpu_accuracy_classical,
    load_gpu_accuracy_gnn_full,
    load_gpu_hierarchical_gnn,
    load_local_accuracy_classical,
    load_local_hierarchical_classical,
    load_merged_accuracy_classical,
    load_merged_accuracy_gnn,
    load_merged_hierarchical_classical,
    load_merged_scalability_classical,
    load_merged_scalability_gnn,
)


def _tex_escape(s: str) -> str:
    return s.replace("\\", "/").replace("_", r"\_").replace("%", r"\%")


def check_approx(name: str, got: float, expected: float, tol: float = 0.02) -> tuple[str, bool]:
    ok = not (np.isnan(got) or np.isnan(expected)) and abs(got - expected) <= tol
    status = "PASS" if ok else "FAIL"
    return f"{name} & {expected:.4f} & {got:.4f} & {tol} & {status}", ok


def _local_accuracy_ami_mean(algo: str, mu: float) -> float:
    loc = load_local_accuracy_classical()
    sub = loc[(loc["algorithm"] == algo) & (np.isclose(loc["mu"], mu, atol=0.005))]
    return float(sub["ami"].mean()) if len(sub) > 0 else float("nan")


def _ami_mean_gpu_gnn_full(algo: str, mu: float) -> float:
    df = load_gpu_accuracy_gnn_full()
    sub = df[(df["algorithm"] == algo) & (np.isclose(df["mu"], mu, atol=0.005))]
    return float(sub["ami"].mean()) if len(sub) else float("nan")


def _hier_mean_micro(df: pd.DataFrame, algo: str, m1: float, m2: float) -> float:
    sub = df[
        (df["algorithm"] == algo)
        & (np.isclose(df["mu1"], m1))
        & (np.isclose(df["mu2"], m2))
    ]
    return float(sub["ami_micro"].mean()) if len(sub) else float("nan")


def _hier_mean_macro(df: pd.DataFrame, algo: str, m1: float, m2: float) -> float:
    sub = df[
        (df["algorithm"] == algo)
        & (np.isclose(df["mu1"], m1))
        & (np.isclose(df["mu2"], m2))
    ]
    return float(sub["ami_macro"].mean()) if len(sub) else float("nan")


def _gnn_hier_micro_row_mean(gn: pd.DataFrame, algo_base: str, m1: float, m2: float) -> tuple[float, float]:
    """Mean ami_micro and ami_macro for ``{algo_base}_micro`` rows at (m1,m2)."""
    key = f"{algo_base}_micro"
    sub = gn[(gn["algorithm"] == key) & (np.isclose(gn["mu1"], m1)) & (np.isclose(gn["mu2"], m2))]
    if len(sub) == 0:
        return float("nan"), float("nan")
    return float(sub["ami_micro"].mean()), float(sub["ami_macro"].mean())


def _local_scalability_ami_mean(algo: str, n: int) -> float:
    df = pd.read_csv(PATHS["local_scalability_classical"])
    df["N"] = df["N"].astype(float).astype(int)
    sub = df[(df["algorithm"] == algo) & (df["N"] == n)]
    if "success" in sub.columns:
        sub = sub[sub["success"] == True]
    return float(sub["ami"].mean()) if len(sub) > 0 else float("nan")


def main() -> int:
    root = pathlib.Path(__file__).parent
    tables_dir = root / "tables"
    tables_dir.mkdir(exist_ok=True)

    lines: list[str] = []
    lines.append(r"\subsection{Automated validation (reproducibility)}")
    lines.append(
        r"This section is generated by \texttt{validate\_lfr\_manuscript.py}. "
        r"It does not trust hand-copied numbers: every check recomputes means from the raw CSV rows."
    )

    # --- Fingerprints ---
    lines.append(r"\subsubsection{Input files and SHA-256 checksums}")
    lines.append(r"\footnotesize")
    lines.append(r"\begin{tabular}{lp{8cm}rr}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Key} & \textbf{Path} & \textbf{Bytes} & \textbf{SHA-256 (prefix)} \\")
    lines.append(r"\midrule")
    all_ok = True
    for key, path in sorted(PATHS.items()):
        fp = file_fingerprint(path)
        exists = fp["exists"]
        if not exists:
            all_ok = False
            lines.append(
                rf"{_tex_escape(key)} & \texttt{{{_tex_escape(str(path))}}} & --- & \textbf{{MISSING}} \\"
            )
            continue
        sha_pfx = fp["sha256"][:16] + r"\ldots"
        path_tt = _tex_escape(pathlib.Path(path).as_posix())
        lines.append(
            rf"{_tex_escape(key)} & \texttt{{{path_tt}}} & {fp['size_bytes']} & \texttt{{{sha_pfx}}} \\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\normalsize")

    # --- Provenance: SBM / Nested SBM / Walktrap ---
    lines.append(r"\subsubsection{Row-level provenance for selected algorithms}")
    cl_merged, prov = load_merged_accuracy_classical()
    prov_map = dict(zip(prov["algorithm"], prov["accuracy_source"]))
    lines.append(
        r"\textbf{SBM} and \textbf{Nested SBM} (accuracy/scalability): rows, sampling grid, and \textbf{runtime} come from the GPU result CSVs; "
        r"\textbf{AMI} is overwritten from the local CSV when the same $\mu$ (accuracy) or $N$ (scalability) exists locally, otherwise AMI stays GPU. "
        rf"Policy strings: SBM \texttt{{{_tex_escape(prov_map.get('sbm', '?'))}}}; "
        rf"Nested SBM \texttt{{{_tex_escape(prov_map.get('nested_sbm', '?'))}}}."
    )
    lines.append("\n\n")
    lines.append(
        r"\textbf{Walktrap} (and DER, GDMP2, SimNet, SVT, Tusk) are absent from that GPU classical CSV; "
        r"their AMI columns are merged from \texttt{local\_accuracy\_classical} "
        r"(\texttt{ClusterNet/Optimized\_algos/benchmarks/lfr/accuracy/results/accuracy\_results.csv}). "
        rf"Example walktrap $\rightarrow$ \texttt{{{_tex_escape(prov_map.get('walktrap', '?'))}}}."
    )

    hier_merged, hier_prov = load_merged_hierarchical_classical()
    hier_map = dict(zip(hier_prov["algorithm"], hier_prov["hierarchical_source"]))
    lines.append(r"\subsubsection{Hierarchical classical AMI provenance}")
    lines.append(
        r"Plain \texttt{sbm} is absent from the hierarchical benchmark CSVs (only nested variants). "
        r"For \textbf{nested\_sbm} and \textbf{nested\_sbm\_coarse}, the GPU hierarchical CSV supplies the grid and \textbf{runtime}; "
        r"\textbf{ami\_micro} / \textbf{ami\_macro} are overwritten from \texttt{local\_hierarchical\_classical} when "
        r"$(\mu_1,\mu_2,\text{realization})$ matches."
    )
    for algo in sorted(AMI_OVERLAY_HIERARCHICAL_CLASSICAL):
        algo_tt = algo.replace("_", r"\_")
        lines.append(
            rf"\texttt{{{algo_tt}}} $\rightarrow$ \texttt{{{_tex_escape(hier_map.get(algo, '?'))}}}."
        )

    # --- Independent GPU vs local overlap (why scaling ``conversion'' is invalid) ---
    lines.append(r"\subsubsection{GPU vs.\ local accuracy files on overlapping algorithms}")
    lines.append(
        r"The GPU and local classical CSVs are \emph{not} guaranteed to be identical draws of LFR graphs "
        r"(seeds / code versions may differ). Therefore \textbf{no single multiplicative ``conversion factor''} "
        r"should be applied to map local AMI to GPU AMI. Below: independent mean AMI at $\mu=0.3$ for algorithms "
        r"present in both files."
    )
    gpu = load_gpu_accuracy_classical()
    loc = load_local_accuracy_classical()
    mu_t = 0.3
    lines.append(r"\begin{tabular}{lrrr}")
    lines.append(r"\toprule")
    lines.append(r"Algorithm & GPU CSV mean AMI & Local CSV mean AMI & $|\Delta|$ \\")
    lines.append(r"\midrule")
    for algo in ["leiden", "louvain", "sbm", "nested_sbm", "fastgreedy"]:
        g = gpu[(gpu["algorithm"] == algo) & (np.isclose(gpu["mu"], mu_t, atol=0.005))]
        l = loc[(loc["algorithm"] == algo) & (np.isclose(loc["mu"], mu_t, atol=0.005))]
        gm = float(g["ami"].mean()) if len(g) else float("nan")
        lm = float(l["ami"].mean()) if len(l) else float("nan")
        diff = abs(gm - lm) if not (np.isnan(gm) or np.isnan(lm)) else float("nan")
        algo_tt = algo.replace("_", r"\_")
        lines.append(rf"\texttt{{{algo_tt}}} & {gm:.4f} & {lm:.4f} & {diff:.4f} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # --- Manuscript headline checks ---
    lines.append(r"\subsubsection{Checks against numbers quoted in the main text}")
    lines.append(r"\begin{tabular}{p{6.5cm}rrrr}")
    lines.append(r"\toprule")
    lines.append(r"Claim & Expected & Got & Tol & Status \\")
    lines.append(r"\midrule")

    gn = load_merged_accuracy_gnn()
    sc_gn = load_merged_scalability_gnn()
    sc_merged, _ = load_merged_scalability_classical()

    checks = []
    for algo in ["sbm", "nested_sbm"]:
        lm = _local_accuracy_ami_mean(algo, 0.5)
        gm = ami_mean(cl_merged, algo, 0.5)
        if not np.isnan(lm):
            checks.append(
                (rf"\texttt{{{algo}}} AMI @ $\mu{{=}}0.5$: merged equals local CSV", lm, gm)
            )
        lm2 = _local_scalability_ami_mean(algo, 500)
        gm2, _ = ami_mean_scalability(sc_merged, algo, 500)
        if not np.isnan(lm2):
            checks.append(
                (rf"\texttt{{{algo}}} scalability AMI @ $N{{=}}500$: merged equals local CSV", lm2, gm2)
            )

    checks.extend(
        [
        (r"Leiden AMI @ $\mu{=}0.5$ (merged classical)", 0.972, ami_mean(cl_merged, "leiden", 0.5)),
        (r"TeamCS AMI @ $\mu{=}0.5$", 1.000, ami_mean(cl_merged, "teamcs", 0.5)),
        (r"Walktrap AMI @ $\mu{=}0.5$", 0.990, ami_mean(cl_merged, "walktrap", 0.5)),
        (r"CPM AMI @ $\mu{=}0.7$ (merged classical)", 0.386, ami_mean(cl_merged, "cpm", 0.7)),
        (r"Node2Vec+KM AMI @ $\mu{=}0.1$", 0.997, ami_mean(gn, "node2vec_gnn", 0.1)),
        (r"DMoN AMI @ $\mu{=}0.5$", 0.186, ami_mean(gn, "dmon_gnn", 0.5)),
        (r"DMoN AMI @ $N{=}25000$ scalability", 0.257, ami_mean_scalability(sc_gn, "dmon_gnn", 25000)[0]),
        (r"Node2Vec AMI @ $N{=}25000$", 0.988, ami_mean_scalability(sc_gn, "node2vec_gnn", 25000)[0]),
        (r"GCN (20\%) AMI @ $N{=}25000$", 0.567, ami_mean_scalability(sc_gn, "gcn_supervised", 25000)[0]),
        (r"GAT (20\%) AMI @ $\mu{=}0.1$ (GPU CSV incl.\ variants)", 0.667, _ami_mean_gpu_gnn_full("gat_supervised", 0.1)),
        (r"GAT (20\%) AMI @ $\mu{=}0.3$", 0.482, _ami_mean_gpu_gnn_full("gat_supervised", 0.3)),
        (r"GAT (20\%) AMI @ $\mu{=}0.5$", 0.121, _ami_mean_gpu_gnn_full("gat_supervised", 0.5)),
        (r"GAT (40\%) AMI @ $\mu{=}0.3$", 0.439, _ami_mean_gpu_gnn_full("gat_supervised_40", 0.3)),
        (r"GAT (60\%) AMI @ $\mu{=}0.3$", 0.347, _ami_mean_gpu_gnn_full("gat_supervised_60", 0.3)),
        (r"GAT (80\%) AMI @ $\mu{=}0.3$", 0.397, _ami_mean_gpu_gnn_full("gat_supervised_80", 0.3)),
        (r"GCN (20\%) AMI @ $\mu{=}0.1$", 0.400, _ami_mean_gpu_gnn_full("gcn_supervised", 0.1)),
        ]
    )

    for name, exp, got in checks:
        tol = 0.001 if ("merged equals local" in name) else 0.02
        row, ok = check_approx(name, got, exp, tol=tol)
        lines.append(row + r" \\")
        all_ok = all_ok and ok

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # --- Hierarchical benchmark (merged classical + GPU GNN) ---
    lines.append(r"\subsubsection{Hierarchical benchmark (Figure~\texttt{fig:lfr\_hierarchical})}")
    lines.append(r"\begin{tabular}{p{7.2cm}rrrr}")
    lines.append(r"\toprule")
    lines.append(r"Claim & Expected & Got & Tol & Status \\")
    lines.append(r"\midrule")

    loc_h = load_local_hierarchical_classical()
    gn_h = load_gpu_hierarchical_gnn()

    h_checks = [
        (
            r"nested\_sbm micro $(0.3,0.3)$: merged == local CSV",
            _hier_mean_micro(loc_h, "nested_sbm", 0.3, 0.3),
            _hier_mean_micro(hier_merged, "nested_sbm", 0.3, 0.3),
        ),
        (
            r"nested\_sbm macro $(0.3,0.3)$ (merged / local overlay)",
            _hier_mean_macro(loc_h, "nested_sbm", 0.3, 0.3),
            _hier_mean_macro(hier_merged, "nested_sbm", 0.3, 0.3),
        ),
        (
            r"Leiden micro $(0.3,0.3)$ (GPU classical, unchanged)",
            0.581,
            _hier_mean_micro(hier_merged, "leiden", 0.3, 0.3),
        ),
        (
            r"Leiden macro $(0.3,0.3)$",
            1.0,
            _hier_mean_macro(hier_merged, "leiden", 0.3, 0.3),
        ),
        (
            r"nested\_sbm micro $(0.3,0.3)$ (main text rounded)",
            0.952,
            _hier_mean_micro(hier_merged, "nested_sbm", 0.3, 0.3),
        ),
        (
            r"nested\_sbm macro $(0.3,0.3)$ (main text rounded)",
            0.619,
            _hier_mean_macro(hier_merged, "nested_sbm", 0.3, 0.3),
        ),
        (
            r"Infomap micro $(0.3,0.3)$",
            0.739,
            _hier_mean_micro(hier_merged, "infomap", 0.3, 0.3),
        ),
        (
            r"Infomap macro $(0.3,0.3)$",
            0.795,
            _hier_mean_macro(hier_merged, "infomap", 0.3, 0.3),
        ),
    ]
    mic_d, mac_d = _gnn_hier_micro_row_mean(gn_h, "dmon_gnn", 0.1, 0.1)
    mic_v, mac_v = _gnn_hier_micro_row_mean(gn_h, "vgae_gnn", 0.1, 0.1)
    mic_m, _ = _gnn_hier_micro_row_mean(gn_h, "mincut_gnn", 0.1, 0.1)

    h_checks.extend(
        [
            (r"DMoN micro-target micro AMI $(0.1,0.1)$", 0.716, mic_d),
            (r"VGAE micro-target micro AMI $(0.1,0.1)$", 0.639, mic_v),
            (r"VGAE micro-target macro AMI $(0.1,0.1)$", 0.342, mac_v),
            (r"MinCut micro-target micro AMI $(0.1,0.1)$ (below 0.1)", 0.05, mic_m),
        ]
    )

    for name, exp, got in h_checks:
        tol = 0.001 if "merged == local" in name or "merged / local" in name else 0.03
        if "MinCut" in name and "below" in name:
            ok = not np.isnan(got) and got < 0.1
            status = "PASS" if ok else "FAIL"
            row = f"{name} & <0.1 & {got:.4f} & --- & {status}"
            lines.append(row + r" \\")
            all_ok = all_ok and ok
            continue
        row, ok = check_approx(name, float(got), float(exp), tol=tol)
        lines.append(row + r" \\")
        all_ok = all_ok and ok

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # --- Supplementary table regeneration match ---
    lines.append(r"\subsubsection{Supplementary tables match script output}")
    acc_disk = (tables_dir / "lfr_accuracy_full.tex").read_text(encoding="utf-8").strip()
    acc_new = gen_accuracy_table().strip()
    sca_disk = (tables_dir / "lfr_scalability_full.tex").read_text(encoding="utf-8").strip()
    sca_new = gen_scalability_table().strip()
    acc_match = acc_disk == acc_new
    sca_match = sca_disk == sca_new
    if not acc_match or not sca_match:
        all_ok = False
    acc_lbl = "PASS" if acc_match else "FAIL"
    sca_lbl = "PASS" if sca_match else "FAIL"
    lines.append(
        rf"Supplementary Table S1 file matches \texttt{{gen\_lfr\_table.py}} output: "
        rf"\textbf{{{acc_lbl}}}. "
        rf"Table S2 match: \textbf{{{sca_lbl}}}. "
        r"If FAIL, run \texttt{python gen\_lfr\_table.py} and commit the updated \texttt{.tex} files."
    )

    lines.append(r"\subsubsection{Coverage limits (interpretive vs.\ tested claims)}")
    lines.append(
        r"Hierarchical classical AMI table above uses merged GPU+local Nested SBM rows; GNN hierarchical AMI comes from "
        r"\texttt{gpu\_hierarchical\_gnn}. Failure-mode commentary ($K$-ratio thresholds) remains qualitative against "
        r"Figure~\texttt{fig:lfr\_cluster\_count}. GPU vs.\ local flat-LFR accuracy overlap at $\mu{=}0.3$ is summarized above."
    )

    lines.append(r"\subsubsection{Overall validation outcome}")
    lines.append(
        rf"\textbf{{Validation score: {'PASS' if all_ok else 'FAIL'}}} "
        r"(all checksums present, manuscript checks within tolerance, supplementary tables in sync)."
    )

    out_tex = tables_dir / "lfr_validation_report.tex"
    out_tex.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_tex}")
    print(f"Overall validation: {'PASS' if all_ok else 'FAIL'}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
